# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Operations
    autoload :Format, 'open_api_sdk/models/operations/format.rb'
    autoload :PostV1TemplatesCreateImageRequestBody, 'open_api_sdk/models/operations/post_v1_templates_createimage_requestbody.rb'
    autoload :PostV1TemplatesCreateImageResponse, 'open_api_sdk/models/operations/post_v1_templates_createimage_response.rb'
    autoload :QueryParamFormat, 'open_api_sdk/models/operations/queryparam_format.rb'
    autoload :GetV1TemplatesSignedurlRequest, 'open_api_sdk/models/operations/get_v1_templates_signedurl_request.rb'
    autoload :GetV1TemplatesSignedurlResponse, 'open_api_sdk/models/operations/get_v1_templates_signedurl_response.rb'
    autoload :GetV1InfoRequest, 'open_api_sdk/models/operations/get_v1_info_request.rb'
    autoload :GetV1InfoResponseBody, 'open_api_sdk/models/operations/get_v1_info_responsebody.rb'
    autoload :GetV1InfoResponse, 'open_api_sdk/models/operations/get_v1_info_response.rb'
  end
end
