# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Shared
    autoload :ErrInternalServerErrorCode, 'open_api_sdk/models/shared/errinternalservererror_code.rb'
    autoload :ErrInternalServerErrorError, 'open_api_sdk/models/shared/errinternalservererror_error.rb'
    autoload :ErrInternalServerError, 'open_api_sdk/models/shared/errinternalservererror.rb'
    autoload :ErrTooManyRequestsCode, 'open_api_sdk/models/shared/errtoomanyrequests_code.rb'
    autoload :ErrTooManyRequestsError, 'open_api_sdk/models/shared/errtoomanyrequests_error.rb'
    autoload :ErrTooManyRequests, 'open_api_sdk/models/shared/errtoomanyrequests.rb'
    autoload :ErrConflictCode, 'open_api_sdk/models/shared/errconflict_code.rb'
    autoload :ErrConflictError, 'open_api_sdk/models/shared/errconflict_error.rb'
    autoload :ErrConflict, 'open_api_sdk/models/shared/errconflict.rb'
    autoload :ErrNotFoundCode, 'open_api_sdk/models/shared/errnotfound_code.rb'
    autoload :ErrNotFoundError, 'open_api_sdk/models/shared/errnotfound_error.rb'
    autoload :ErrNotFound, 'open_api_sdk/models/shared/errnotfound.rb'
    autoload :ErrForbiddenCode, 'open_api_sdk/models/shared/errforbidden_code.rb'
    autoload :ErrForbiddenError, 'open_api_sdk/models/shared/errforbidden_error.rb'
    autoload :ErrForbidden, 'open_api_sdk/models/shared/errforbidden.rb'
    autoload :Code, 'open_api_sdk/models/shared/code.rb'
    autoload :Error, 'open_api_sdk/models/shared/error.rb'
    autoload :ErrUnauthorized, 'open_api_sdk/models/shared/errunauthorized.rb'
    autoload :Modification, 'open_api_sdk/models/shared/modification.rb'
    autoload :Security, 'open_api_sdk/models/shared/security.rb'
  end
end
