# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  autoload :Bannerify, 'open_api_sdk/bannerify'
  autoload :Shared, 'open_api_sdk/models/shared'
  autoload :Operations, 'open_api_sdk/models/operations'

end

require_relative 'open_api_sdk/utils/t'
require_relative 'open_api_sdk/utils/utils'
require_relative 'open_api_sdk/utils/metadata_fields'
require_relative 'open_api_sdk/sdkconfiguration'
