workflowVersion: 1.0.0
sources:
    bannerify-OAS:
        inputs:
            - location: https://api.bannerify.co/openapi
        registry:
            location: registry.speakeasyapi.dev/bannerify/bannerify/bannerify-oas
targets:
    bannerify:
        target: ruby
        source: bannerify-OAS
