# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # Code - A machine readable error code.
    class Code < T::Enum
      enums do
        UNAUTHORIZED = new('UNAUTHORIZED')
      end
    end

  end
end
