# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ErrConflictCode - A machine readable error code.
    class ErrConflictCode < T::Enum
      enums do
        CONFLICT = new('CONFLICT')
      end
    end

  end
end
