# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ErrForbiddenCode - A machine readable error code.
    class ErrForbiddenCode < T::Enum
      enums do
        FORBIDDEN = new('FORBIDDEN')
      end
    end

  end
end
