# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ErrInternalServerErrorCode - A machine readable error code.
    class ErrInternalServerErrorCode < T::Enum
      enums do
        INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
      end
    end

  end
end
