# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ErrNotFoundCode - A machine readable error code.
    class ErrNotFoundCode < T::Enum
      enums do
        NOT_FOUND = new('NOT_FOUND')
      end
    end

  end
end
