# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ErrTooManyRequestsCode - A machine readable error code.
    class ErrTooManyRequestsCode < T::Enum
      enums do
        TOO_MANY_REQUESTS = new('TOO_MANY_REQUESTS')
      end
    end

  end
end
