# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Security < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :bearer_auth, ::String, { 'security': { 'scheme': true, 'type': 'apiKey', 'sub_type': 'query', 'field_name': 'apiKey' } }


      sig { params(bearer_auth: ::String).void }
      def initialize(bearer_auth: nil)
        @bearer_auth = bearer_auth
      end
    end
  end
end
