# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Format < T::Enum
      enums do
        PNG = new('png')
        SVG = new('svg')
      end
    end

  end
end
