# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1InfoRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :api_key, ::String, { 'query_param': { 'field_name': 'apiKey', 'style': 'form', 'explode': true } }


      sig { params(api_key: ::String).void }
      def initialize(api_key: nil)
        @api_key = api_key
      end
    end
  end
end
