# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1TemplatesSignedurlRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :api_key_md5, ::String, { 'query_param': { 'field_name': 'apiKeyMd5', 'style': 'form', 'explode': true } }

      field :sign, ::String, { 'query_param': { 'field_name': 'sign', 'style': 'form', 'explode': true } }

      field :template_id, ::String, { 'query_param': { 'field_name': 'templateId', 'style': 'form', 'explode': true } }

      field :debug, T.nilable(::String), { 'query_param': { 'field_name': '_debug', 'style': 'form', 'explode': true } }

      field :format, T.nilable(::OpenApiSDK::Operations::QueryParamFormat), { 'query_param': { 'field_name': 'format', 'style': 'form', 'explode': true } }

      field :modifications, T.nilable(::String), { 'query_param': { 'field_name': 'modifications', 'style': 'form', 'explode': true } }

      field :nocache, T.nilable(::String), { 'query_param': { 'field_name': 'nocache', 'style': 'form', 'explode': true } }


      sig { params(api_key_md5: ::String, sign: ::String, template_id: ::String, debug: T.nilable(::String), format: T.nilable(::OpenApiSDK::Operations::QueryParamFormat), modifications: T.nilable(::String), nocache: T.nilable(::String)).void }
      def initialize(api_key_md5: nil, sign: nil, template_id: nil, debug: nil, format: nil, modifications: nil, nocache: nil)
        @api_key_md5 = api_key_md5
        @sign = sign
        @template_id = template_id
        @debug = debug
        @format = format
        @modifications = modifications
        @nocache = nocache
      end
    end
  end
end
