# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostV1TemplatesCreateImageResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # A image file
      field :bytes, T.nilable(::String)
      # This response is sent when a request conflicts with the current state of the server.
      field :err_conflict, T.nilable(::OpenApiSDK::Shared::ErrConflict)
      # The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
      field :err_forbidden, T.nilable(::OpenApiSDK::Shared::ErrForbidden)
      # The server has encountered a situation it does not know how to handle.
      field :err_internal_server_error, T.nilable(::OpenApiSDK::Shared::ErrInternalServerError)
      # The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.
      field :err_not_found, T.nilable(::OpenApiSDK::Shared::ErrNotFound)
      # The user has sent too many requests in a given amount of time ("rate limiting")
      field :err_too_many_requests, T.nilable(::OpenApiSDK::Shared::ErrTooManyRequests)
      # Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
      field :err_unauthorized, T.nilable(::OpenApiSDK::Shared::ErrUnauthorized)
      # The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
      field :one_of, T.nilable(::Object)
      # A image file
      field :res, T.nilable(::String)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, bytes: T.nilable(::String), err_conflict: T.nilable(::OpenApiSDK::Shared::ErrConflict), err_forbidden: T.nilable(::OpenApiSDK::Shared::ErrForbidden), err_internal_server_error: T.nilable(::OpenApiSDK::Shared::ErrInternalServerError), err_not_found: T.nilable(::OpenApiSDK::Shared::ErrNotFound), err_too_many_requests: T.nilable(::OpenApiSDK::Shared::ErrTooManyRequests), err_unauthorized: T.nilable(::OpenApiSDK::Shared::ErrUnauthorized), one_of: T.nilable(::Object), res: T.nilable(::String)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, bytes: nil, err_conflict: nil, err_forbidden: nil, err_internal_server_error: nil, err_not_found: nil, err_too_many_requests: nil, err_unauthorized: nil, one_of: nil, res: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @bytes = bytes
        @err_conflict = err_conflict
        @err_forbidden = err_forbidden
        @err_internal_server_error = err_internal_server_error
        @err_not_found = err_not_found
        @err_too_many_requests = err_too_many_requests
        @err_unauthorized = err_unauthorized
        @one_of = one_of
        @res = res
      end
    end
  end
end
